spring:
  main:
    allow-bean-definition-overriding: true

  config:
    activate:
      on--profile:

  application:
    name: simple-vue

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=Asia/Seoul
    username: vue
    password: 1234
